### ISSUE TITLE
Add button for copying code snippets into clipboard

### ISSUE THREAD

**Issue by amotl** [crate/crate-docs-theme#258]
Hi there,

coming from https://github.com/crate/twd-archive/issues/40, we are considering to add a "Copy snippet" button to the documentation.

With kind regards,
Andreas.

**Comment by amotl** [comment]
@msbt suggested:

The problem with the current code snippets (at least those that I just saw): They're not copy/pastable, like https://crate.io/docs/crate/howtos/en/latest/best-practices/migrating-from-mysql.html#id1 - what are the `...` doing there? 

Just did a quick search, what about this Sphinx addon?

- https://github.com/choldgraf/sphinx-copybutton
- https://sphinx-copybutton.readthedocs.io/en/latest/

On WordPress, we use [prism.js](https://prismjs.com/plugins/copy-to-clipboard/).

**Comment by norosa** [comment]
the biggest issue we will have with this is removing the following:

- the command prompts (i.e., `cr>` and `$`) - this is necessary because if you copy and paste a query or a command you need to either a) select the text carefully so as to not copy the prompt, or b) remove the prompt manually after copying and pasting

- the `...` bits. they are there because the tool we use for doctests requires that syntax for multi-line inputs/output (i.e., a tool that runs the queries against an actual running instance of CrateDB and verifies that the output matches the output in the example). if you copy and paste a multi-line query/command you have to remove the `...` bits for it to work
 
- the example output (i.e., the lines that appear after the query or command showing the output you could expect if you run the query/command yourself). if I copy the text from an example, I do not want the query/command output to be included, because my goal is to paste the query/command by itself and observe the output it actually produces

**Comment by amotl** [comment]
The great thing is that `sphinx-copybutton` already supports removing those kinds of prompts when copying.

**Comment by amotl** [comment]
Apparently, this feature is not yet active on the reference documentation at https://crate.io/docs/crate/reference/.

**Comment by norosa** [comment]
@amotl I have investigated this issue and found the cause. see:

- https://github.com/crate/crate/pull/11466
- https://github.com/crate/croud/pull/335

**Comment by norosa** [comment]
bonus PR: https://github.com/crate/crate-docs-theme/pull/296

**Comment by amotl** [comment]
This feature has been integrated successfully. Thanks a stack to everyone who collaborated! 👍
