### ISSUE TITLE
Broken rendering?

### ISSUE THREAD

**Issue by amotl** [crate/crate-docs-theme#277]
Hi there,

@proddata just shared this screenshot with me. According to his report, it only happens on https://crate.io/docs/crate/tutorials/. He has been able to verify it on two different devices using two different internet connections. On the other hand, I have not been able to reproduce it in any way.

![image](https://user-images.githubusercontent.com/453543/119689047-d37c6600-be48-11eb-9acd-449dbdd4419b.png)

With kind regards,
Andreas.

**Comment by msbt** [comment]
Ok something is not right, there are several errors on various docs pages. We meant to test the new version on a single repo, can we roll back and do that to see what's going on here? @amotl @norosa 

getting
`Uncaught TypeError: $.cookie is not a function`
two more json errors and also
`Error loading Read the Docs footer readthedocs-doc-embed.js`
and 
`Error registering page view readthedocs-doc-embed.js`

**Comment by msbt** [comment]
The initial rendering issue should be resolved (this happens when you try to include an already gzipped document, that's why the Fastly thing should have happened first. I've added an empty file as include and will rename the proper one when the new config is live. Either way, there are some other issues mentioned above that need addressing.

**Comment by msbt** [comment]
@amotl I did a bit of comparing and it seems one of the issues is that we load jquery too late, this needs to be loaded before the bundled js file which includes some jquery functions (e.g. the cookie thing). The others could be also related to that, since there are some jquery messages in the debugger.

**Comment by amotl** [comment]
Thank you for figuring this out! We probably missed this detail because the corresponding code has not been run in the local sandbox when just looking at the examples, right?

**Comment by msbt** [comment]
Yes, the cookie thing is only used when a segment id is supplied (`{% if theme_tracking_segment_id %}` - so only on production) and rtd is probably only in use when rendered there, at least I think I didn't see any errors while testing.

**Comment by amotl** [comment]
The `Uncaught TypeError: $.cookie is not a function` error should be gone now.

- https://crate.io/docs/crate/tutorials/
- https://crate.io/docs/crate/howtos/

Do you know why it would not work on https://crate.io/docs/crate/reference/ yet?
