### ISSUE TITLE
CI: RTD build is useless

### ISSUE THREAD

**Issue by amotl** [crate/crate-docs-theme#351]
Hi there,

while working on #349, I found the RTD build on CI to be broken [^1]. However, it is not related to Sphinx 5, because it already happens beforehand. I've verified it with #350 and the outcome is likewise broken [^2].

For the RTD build, the [crate-docs](https://github.com/crate/crate-docs) project is used. However, it is apparently not suitable for being inspected on CI. It would be so sweet if it could be used as a canary for verifying updates to the theme without needing them to be propagated downstream, no?

With kind regards,
Andreas.

[^1]: https://crate-docs-theme--349.org.readthedocs.build/en/349/
[^2]: https://crate-docs-theme--350.org.readthedocs.build/en/350/

/cc @msbt

**Comment by msbt** [comment]
@amotl I've compared the raw logs from the [Run build before upgrading to Sphinx 5 docs #338](https://github.com/crate/crate-docs-theme/runs/7216601509?check_suite_focus=true) build with some of earlier runs (e.g. [SEO improvements (content wider than screen) and other smaller fixes build #283](https://github.com/crate/crate-docs-theme/runs/7132036275?check_suite_focus=true)) and it seems that there are a few things missing.

I can't find the line with `.env/bin/pip3 install -r requirements.txt` which subsequently would install `nodeenv` and all the webpack stuff. It also says `Using legacy 'setup.py install' for livereload, since package 'wheel' is not installed.` which it doesn't on the older build. I reckon that's why the `bundle/main.js` with its assets is missing.

**Comment by amotl** [comment]
Now I am seeing it. I think there are two anomalies.

### Application bundle missing
This is what you reported, @msbt, right?
```
GET https://crate-docs-theme--349.org.readthedocs.build/en/349/_static/bundle/main.js?ver=0.24.5
Status: 404 Not Found
```

### Wrong project association
I  believe the documentation of `crate-docs-theme` thinks it is both associated with the project `crate-docs-theme`, as well as `fake`, which looks like it is not published at the moment.
```
GET https://crate.io/docs/fake/_/static/javascript/readthedocs-doc-embed.js?ver=0.24.5
Status: 404 Not Found
```

### Outlook
1. Investigate why the application bundle file `bundle/main.js` is not present.
2. Investigate the misguidedness of the project name/url, wrt. `crate-docs-theme` vs. `fake`.

**Comment by msbt** [comment]
@amotl yes, exactly, I was investigating why main.js (and related assets) from the webpack bundler aren't present and those were the attempts to figure out why. Thanks for checking those out!

**Comment by amotl** [comment]
> Investigate why the application bundle file `bundle/main.js` is not present.

Oh it just occurred to me that this would actually be expected. While the JavaScript/CSS bundle is part of the package published to PyPI, it is obviously missing on a bare repository checkout and would need to be bundled beforehand.

So, this is actually a natural implication of #255. `webpack` probably can't run on RTD, so we will have to come up with a different solution.

**Comment by amotl** [comment]
GH-379 fixed this issue, so rendering previews and finals on RTD works well now.

-- https://crate-docs-theme.readthedocs.io/
