### ISSUE TITLE
Version chooser: Can the "latest" version be emphasized?

### ISSUE THREAD

**Issue by amotl** [crate/crate-docs-theme#368]
Hi.

@matriv had a suggestion over at https://github.com/crate/infrastructure/pull/2993#issuecomment-1436626845:

> It would be nice, for the users, to have "which is the latest stable release" visible to the users, and the best way imho opinion is to list all available version we want in the drop down and have for example `0.29 (latest)` entry to mark the latest. I don't know if that's even feasible with RTD?

What are your thoughts about this, @msbt?

With kind regards,
Andreas.

**Comment by msbt** [comment]
@amotl not sure if this is doing to work, because for whatever reason (I think you explained that to me a while ago), the latest version and the latest numbered version aren't always the same, like https://crate.io/docs/pdo/en/latest/ is not the same as https://crate.io/docs/pdo/en/1.0/ even though it's the latest numbered release available. If we figure that out, we can plan ahead.

Maybe @michaelkremmel can chime in as well from a SEO perspective. Will the url still be `/latest` or `/0.29` in your scenario?

**Comment by amotl** [comment]
Hi again. I just picked this up so it would not be forgotten. However, due to lack of bandwidth, I am closing this. Please feel free to re-open if you think it should be handled better.
