### ISSUE TITLE
Documentation search results - latest version documentation not always the first result

### ISSUE THREAD

**Issue by karynzv** [crate/crate-docs-theme#373]
Current behavior:
When searching in the documentation, the result can include pages referring to older versions of CrateDB even before the latest versions, as seen in the image below.

<img width="1184" alt="Screenshot 2023-05-04 at 11 00 33" src="https://user-images.githubusercontent.com/4229270/236186648-827b8743-4cbe-40dc-b6a2-62c7e476bd11.png">

Expected behavior:
When searching for a given topic in the documentation, the pages related to the latest release should be listed first. Unless, of course, the user explicitly added a given version on the search query. In that case, the search result should have the referred version documentation first.

**Comment by msbt** [comment]
@karynzv thanks to @WalBeh the 3.3 reference should be removed from the search results now, please test and lmk if this is what we wanted.

**Comment by amotl** [comment]
The results look much better now. However, on the third result position, there is still a blast from the past. Can you do something more about it?

![image](https://github.com/crate/crate-docs-theme/assets/453543/5f156a16-2e78-4a28-96d4-e80e231e6a94)

-- https://crate.io/docs/crate/reference/en/latest/search.html?q=data+type

**Comment by msbt** [comment]
hmhm, now it's getting tricky again, how many repos with old versions do we have? Would it make more sense to include only `/latest/` paths or wouldn't that work because of the reference-redirect?

**Comment by msbt** [comment]
I'm not entirely sure where that page comes from, since it's a v0,x and we don't even have that in the dropdown... But seeing that now, maybe excluding just 3.3 was the wrong approach.

**Comment by amotl** [comment]
Thanks for your investigations. I don't know much about the topic, and the corresponding tuning knobs. I just wanted to make you aware what I observed when also conducting the search now, after you made some adjustments.

In this case, the single straw item pointing to a 0.52.1 resources is funny, but apparently does not hurt too much, because the link will be redirected appropriately by the redirection rule phalanx.

So, feel free to close this ticket, and open different ones as you see fit.

**Comment by msbt** [comment]
`0.52.1` is now removed as well, lmk if any others need excluding
