### ISSUE TITLE
Move search button to the top right corner

### ISSUE THREAD

**Issue by geragray** [crate/crate-docs-theme#479]
To search through the docs user would have to click on the large rectangular button above TOC on the left side of the page. Multiple users reported it as very counterintuitive, some didn't even notice the button at all.

Proposal
* Add a button with a "looking glass" icon next to the cog in the top right corner of the page
* Clicking on the button leads the user to the current search page
* Remove the "search" rectangular button on the left

<img width="1258" alt="Screenshot 2024-04-09 at 15 08 03" src="https://github.com/crate/crate-docs-theme/assets/1540340/ba5448c4-1ee4-487a-aa86-886b5ec36195">

**Comment by amotl** [comment]
## Thoughts
After replacing Google Search with Algolia (thanks, @msbt), the search bar has a much better appearance and as such, is more appealing to use and catch the focus of our dear readers.

In this spirit, because more work would need further thoughts, we are closing this. Feel free to re-open when applicable.

## References
- https://github.com/crate/tech-writing/issues/401
- https://github.com/crate/crate-docs-theme/pull/481
