### ISSUE TITLE
Jira Document - environment of our docs

### ISSUE THREAD

**Issue by matkuliak** [crate/crate-docs-theme#496]
We'd like to have a single document, for now in Jira it seems, that would be a good starting point for someone who'd like to contribute or even maintain all aspects. So it should eventually get more details than for example https://github.com/crate/cloud-docs/blob/main/DEVELOP.rst

---

https://crateio.atlassian.net/wiki/spaces/TeamDBCloud/pages/818282503/Documentation+environment+overview

**Comment by amotl** [comment]
There is no JIRA document in Sphinx or in crate-docs-theme. Can you clarify?

**Comment by matkuliak** [comment]
Hi. Description updated.
It's something I'd like to discuss with you when you return, will expand on it then

**Comment by amotl** [comment]
Confluence is definitively the wrong place, only contains fragments of the whole story, and will easily get stale, because pages on Wikis will always go down that route, and stink.

Please use one of those spots to improve the documentation for technical writers, both internal or external, both newbies or oldfarts. Thanks!

- https://crate-docs-theme.readthedocs.io/
- https://github.com/crate/tech-writing

**Comment by matkuliak** [comment]
I'd agree with the Wiki assessment. We can discuss the best way to go about it later

**Comment by amotl** [comment]
Sure. Just submit patches about improvements to the two spots enumerate above. Thanks.
